### ISSUE TITLE
No README.pod in metacpan/release

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl-fftw3#4]
[The metacpan landing page for this module](https://metacpan.org/release/PDL-FFTW3) doesn't show any documentation right off the bat.  It renders correctly [here](https://metacpan.org/pod/release/ETJ/PDL-FFTW3-0.06/README.pod), though.  I'm not sure if that is normal behavior or not.

**Comment by mohawk2** [comment]
I don't think README files get displayed on the release page - PDL's doesn't either. Therefore, I think this is normal and this could be closed? :-)
